name: Test docker

on:
  push:
    branches: [main]
    paths: [.github/workflows/test-dockerlogin.yml]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockeraddr:
          - 'docker.io'
          - 'docker.com'
          - '52.1.179.226'
          - '52.203.94.253'
          - '34.200.152.9'
      fail-fast: false

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ matrix.dockeraddr }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
